### PR TITLE
1.4.1

### PR DESCRIPTION
**Pull request by megies**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

closes #5 
closes #4 
closes #3

### CODE REVIEW

**Comment by megies** [comment]
@conda-forge-admin, please rerender

**Comment by megies** [comment]
@marcelotrevisani, can you push the button on this one? Current pytest-json-report version on conda-forge errors out in our tests, and I'd rather have it updated in conda-forge than to put some `pip install` in our recipe. =)

**Comment by bollwyvl** [comment]
If this package is important to you, and you are finding @conda-forge/pytest-json-report unresponsive: you may wish to add yourself as a maintainer (and re-render). the already-overtaxed conda-forge core is much more likely to intercede, then, on your behalf... though may still request you wait a while (usually a week)  for the current maintainers to respond.

**Comment by megies** [comment]
> you may wish to add yourself as a maintainer (and re-render)

I don't have a problem with that.
Honestly, I'm really surprised that not more people seem to use it (at least through conda forge?). We've had our own [test reporting framework for almost ten years](https://tests.obspy.org/) and just recently switched from unittest to plain pytest completely and thus also switched to using this json report plugin for pytest.

**Comment by megies** [comment]
@conda-forge-admin, please rerender

**Comment by megies** [comment]
If anybody with push rights sees this, would appreciate them hitting the merge button. The only maintainer hasn't merged the really unproblematic bot PRs for updates in almost a year now, so I'd be inclined to consider this feedstock an orphan until this gets merged.

**Comment by megies** [comment]
@conda-forge/core, need help to get this package out of its orphaned state, please. Don't wanna be pushy but I don't think waiting any longer on the sole maintainer here will do any good after a year of no actions in this feedstock. Added myself as maintainer so it's really only about hitting this green button down below once.

**Comment by wolfv** [comment]
thanks for helping out!

**Comment by megies** [comment]
Thanks!

**Pull request merged**
